### Q1. What are the benefits of the built-in array package, if any?

Python has a number of built-in data structures, such as arrays. Arrays give us a way to store and organize data, and we can use the built-in Python methods to retrieve or change that data. For example, if you have a list of student names that you want to store, you may want to store them in an array.

The NumPy arrays takes significantly less amount of memory as compared to python lists. It also provides a mechanism of specifying the data types of the contents, which allows further optimisation of the code.

### Q2. What are some of the array package's limitations?

Unlike arrays, lists are able to store elements belonging to different data types and are faster. Typically, the array module is required for interfacing with C code. It is typically advised to avoid using arrays in Python. However, that doesn’t mean that you can’t learn them.

In programming, an array is a homogenous (belonging to the same data type) collection of elements. Unlike languages like C++, Java, and JavaScript, arrays aren't among the built-in Python data structures. Although Python doesn't have built-in support for arrays, that doesn't stop programmers from implementing them.

### Q3. Describe the main differences between the array and numpy packages.

Numpy is the core library for scientific computing in Python. ... A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.


### Q4. Explain the distinctions between the empty, ones, and zeros functions.

numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.

Parameters :
-> shape : Number of rows
-> order : C_contiguous or F_contiguous
-> dtype : [optional, float(by Default)] Data type of returned array.  

In [5]:
# Python Programming illustrating
# numpy.empty method
  
import numpy as ineuron
  
b = ineuron.empty(2, dtype = int)
print("Matrix b : \n", b)
  
a = ineuron.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
  
c = ineuron.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


The numpy.ones() function returns a new array of given shape and type, with ones.

Parameters :

shape : integer or sequence of integers
order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
dtype : [optional, float(byDeafult)] Data type of returned array.  

ndarray of ones having given shape, order and datatype.

In [6]:
# Python Programming illustrating
# numpy.empty method
  
import numpy as ineuron
  
b = ineuron.empty(2, dtype = int)
print("Matrix b : \n", b)
  
a = ineuron.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
  
c = ineuron.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


The numpy.zeros() function returns a new array of given shape and type, with zeros.

numpy.zeros(shape, dtype = None, order = 'C')

shape : integer or sequence of integers
order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
dtype : [optional, float(byDeafult)] Data type of returned array.

ndarray of zeros having given shape, order and datatype.



In [4]:
# Python Program illustrating
# numpy.zeros method
  
import numpy as ineuron
  
b = ineuron.zeros(2, dtype = int)
print("Matrix b : \n", b)
  
a = ineuron.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
  
c = ineuron.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

In [9]:
import numpy as np

s=np.fromfunction(lambda i,j:j*i,(4,4),dtype=int)
s

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [10]:
callable(s)

False

In general, a callable is something that can be called. This built-in method in Python checks and returns True if the object passed appears to be callable, but may not be, otherwise False.
Syntax:

callable(object)
The callable() method takes only one argument, an object and returns one of the two values:

returns True, if the object appears to be callable.
returns False, if the object is not callable.
Note: There may be few cases where callable() returns true, but the call to object fails. But if a case returns False, calling object will never succeed.

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

In this article, we will discuss different ways to add / append single element in a numpy array by using append() or concatenate() or insert() function. Use append() to add an element to Numpy Array. Use concatenate() to add an element to Numpy Array. Use insert() to add an element to Numpy Array.

In [12]:
np.array((2,3,4))+3
# Yes it is possible.

array([5, 6, 7])

### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [13]:
s=10
s+=np.array((1,23))

s

array([11, 33])

Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization.

### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

The elements of a NumPy array, or simply an array, are usually numbers, but can also be boolians, strings, or other objects. When the elements are numbers, they must all be of the same type. For example, they might be all integers or all floating point numbers.

In [14]:
np.array(('r','o','h','a','n','b','a','g','u','l','w','a','r'))

array(['r', 'o', 'h', 'a', 'n', 'b', 'a', 'g', 'u', 'l', 'w', 'a', 'r'],
      dtype='<U1')

With a 64-bit Python installation, and 64 GB of memory, a Python 2 string of around 63 GB should be quite feasible. If you can upgrade your memory much beyond that, your maximum feasible strings should get proportionally longer. But this comes with a hit to the runtimes.

Use Python's built-in max() function with a key argument to find the longest string in a list. Call max(lst, key=len) to return the longest string in lst using the built-in len() function to associate the weight of each string—the longest string will be the maximum.

### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

multiply() in Python. numpy. multiply() function is used when we want to compute the multiplication of two array. It returns the product of arr1 and arr2, element-wise.

In [15]:
np.array((1,2,34))*np.array((0,0,0))

array([0, 0, 0])

To add the two arrays together, we will use the numpy. add(arr1,arr2) method. In order to use this method, you have to make sure that the two arrays have the same length. If the lengths of the two arrays are​ not the same, then broadcast the size of the shorter array by adding zero's at extra indexes.

In [16]:
np.array((1,2,34))+np.array((0,0,0))

array([ 1,  2, 34])

### Q10. What is the best way to use a Boolean array to mask another array?

Boolean masking is typically the most efficient way to quantify a sub-collection in a collection. Masking in python and data science is when you want manipulated data in a collection based on some criteria. The criteria you use is typically of a true or false nature, hence the boolean part.

Boolean Arrays as Masks
In the preceding section we looked at aggregates computed directly on Boolean arrays. A more powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves. Returning to our x array from before, suppose we want an array of all values in the array that are less than, say, 5:

In [18]:
all(np.array((True,True)))

True

In [19]:
all(np.array((True,True,False,False)))

False

### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [20]:
a=np.arange(1,101)

In [21]:
np.std(a)

28.86607004772212

In [22]:
from scipy import stats

In [23]:
stats.tstd(a)

29.011491975882016

In [24]:
import pandas as pd
pd.Series(a).std()   

29.011491975882016

### 12. What is the dimensionality of a Boolean mask-generated array?

It has only sigle true false result that is it has (1,1) shape.